version: '2.23'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        ports:
            -  "8080:80"
        restart: always
        volumes:
            -   .:/var/www
            -   ./docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel-network

    mysql:
        image: mysql
        container_name: mysql-container
        restart: always
        ports:
            -   "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD : root
        volumes:
            -   mysql-data:/var/lib/mysql
        networks:
            - laravel-network


    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        ports:
            -   "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        networks:
            - laravel-network
        depends_on:
            -   mysql






    app:
        build: .
        container_name: laravel-app
        restart: always
        ports:
            - "9000:9000"
        volumes:
            -   .:/var/www

        networks:
            - laravel-network

        depends_on:
            -   mysql





networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:









